### ISSUE TITLE
SW1: Create abstract version of .NET template generator, and update .NET generator to use abstract library

### ISSUE THREAD

**Issue by thill-odi** [openactive/models-lib#2]
3d

**Comment by ylt** [comment]
@nickevansuk 

Ah, in the current state it's the same generator as the .NET one. The code has been broken into a main class, with the .NET specific logic inheriting it but it's still a little rough. All the methods that were there are still in there (at least for now). It should remain in there :)

**Comment by nickevansuk** [comment]
ok super :)

**Comment by ylt** [comment]
Implemented in #4
