### ISSUE TITLE
Document how to regenerate the the PHP and Ruby libraries when the models change

### ISSUE THREAD

**Issue by nickevansuk** [openactive/models-lib#27]
Also would someone be able to write a quick few bullet points on what we need to do to regenerate the models for **both** PHP and Ruby, e.g.
- git clone repo Y
- Run the https://github.com/openactive/models-lib with a destination folder of X to replace the files in folder Z
- Run the tests by using the commands A
- If the tests pass, then do B to update the repo in the package manager

**Comment by ylt** [comment]
https://github.com/openactive/models-ruby/pull/26
https://github.com/openactive/models-php/pull/47

**Comment by nickevansuk** [comment]
Looks good!
