### ISSUE TITLE
Fix directory of generated files for PHP library

### ISSUE THREAD

**Issue by nickevansuk** [openactive/models-lib#49]
Fix directory/references for generated files as noted here: openactive/models-php#79

Perhaps the issue is about the references rather than the directories?

**Comment by kjlloydie** [comment]
Potentially related: [openactive/models-php#84](https://github.com/openactive/models-php/issues/84) - the filename 3DModel.php is inconsistent with the naming of the ThreeDModel class, resulting in an inability to generate optimized autoload files in composer.

**Comment by nickevansuk** [comment]
Original issue closed by #55, @kjlloydie I've reraised your comment as a separate issue #56
